# Generated by Django 6.0.3 on 2026-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name (RU)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
