# Generated by Django 6.0.3 on 2026-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('genres', models.ManyToManyField(related_name='tracks', to='main.genre', verbose_name='Жанры')),
            ],
        ),
    ]
