# Generated by hand to align DB with models.py
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="music/tracks/"),
        ),
    ]
